### ISSUE TITLE
Maybe an Orphan instance for Compose?

### ISSUE THREAD

**Issue by jwiegley** [ekmett/distributive#10]
I find this handy from time to time:

``` haskell
instance (Distributive f, Monad f, Monad m, Functor m)
         => Monad (Compose f m) where
    return x = Compose $ return (return x)
    Compose m >>= f = Compose $
        join $ liftM ((liftM join . distribute) . liftM (getCompose . f)) m
```

Maybe worth having the orphan instance?

**Comment by ekmett** [comment]
This isn't canonical. There are several variants on such a construction.

http://web.cecs.pdx.edu/~mpj/pubs/RR-1004.pdf

These really should life somewhere else on another data type like they did in:

https://hackage.haskell.org/package/category-extras-0.53.5/docs/src/Control-Functor-Pointed-Composition.html#PointedCompF

but as they only need a Monad a distributive or absorption law and a Pointed functor, that is likely `pointed`, and as they are nigh unusable in practice, and there are many, I'm not that eager to standardize them.

**Comment by jwiegley** [comment]
The variants listed in Jones paper are about different choices for how to provide `Distributive` (i.e., the 3 or 4 different combinators for weakening requirements liked `prod`), but I don't think they propose alternative implementations given a function `f (g x) -> g (f x)`.  In all cases, as I understand it, the goal is to rewrite `g (f (g (f x)))` to `g (f (f (g x)))` so that two joins will do it.

What do you mean by "night unusable in practice"?
