### ISSUE TITLE
Make it compatible with Cabal 1.25 (bundled with GHC 8.2)

### ISSUE THREAD

**Issue by Mikolaj** [ekmett/distributive#21]
Please see https://github.com/haskell/cabal/issues/4157#issuecomment-266992512

**Comment by ocharles** [comment]
Does this package even need a custom `Setup.hs`?

**Comment by RyanGlScott** [comment]
I've uploaded [`distributive-0.5.2`](http://hackage.haskell.org/package/distributive-0.5.2), which works out of the box with `Cabal-1.25`.
