### ISSUE TITLE
document laws?

### ISSUE THREAD

**Issue by matthewleon** [ekmett/distributive#29]
I see on this reddit thread that you've listed two laws: https://www.reddit.com/r/haskell/comments/4cmjeg/a_law_for_distributive/

```
fmap f = runIdentity . collect (Identity . f)
fmap distribute . collect f = getCompose . collect (Compose . f)
```

Might it be worth including them in the documentation for reference?

**Comment by RyanGlScott** [comment]
[Here they are.](https://github.com/ekmett/distributive/blob/6b6cc5ff5414ae3aca72ba33eb7cd9521ed423b3/src/Data/Distributive.hs#L97-L98)

**Comment by matthewleon** [comment]
Indeed. They just slipped my eye. Thanks for pointing it out and my apologies for wasting your time.
