### ISSUE TITLE
Failed to build on debian 8

### ISSUE THREAD

**Issue by Ulrar** [ekmett/distributive#33]
Hi,

I have a clean debian 8 installed and I'm trying to install dependencies for an app I'm developing.
I get this error when it gets to distributive : 

```
distributive-0.5.2 failed during the configure step. The exception was:
user error (/usr/lib/ghc/unix-2.6.0.1/libHSunix-2.6.0.1.a(HsUnix.o): In
function `__hsunix_ptsname':
(.text+0x110): multiple definition of `__hsunix_ptsname'
/home/lemonn_k/.cabal/lib/x86_64-linux-ghc-7.6.3/unix-2.7.2.1/libHSunix-2.7.2.1.a(HsUnix.o):(.text+0x20):
first defined here
/usr/lib/ghc/unix-2.6.0.1/libHSunix-2.6.0.1.a(HsUnix.o): In function
`__hsunix_grantpt':
(.text+0x120): multiple definition of `__hsunix_grantpt'
/home/lemonn_k/.cabal/lib/x86_64-linux-ghc-7.6.3/unix-2.7.2.1/libHSunix-2.7.2.1.a(HsUnix.o):(.text+0x30):
first defined here
/usr/lib/ghc/unix-2.6.0.1/libHSunix-2.6.0.1.a(HsUnix.o): In function
`__hsunix_unlockpt':
(.text+0x130): multiple definition of `__hsunix_unlockpt'
/home/lemonn_k/.cabal/lib/x86_64-linux-ghc-7.6.3/unix-2.7.2.1/libHSunix-2.7.2.1.a(HsUnix.o):(.text+0x40):
first defined here
/usr/lib/ghc/unix-2.6.0.1/libHSunix-2.6.0.1.a(HsUnix.o): In function
`__hsunix_push_module':
(.text+0x140): multiple definition of `__hsunix_push_module'
/home/lemonn_k/.cabal/lib/x86_64-linux-ghc-7.6.3/unix-2.7.2.1/libHSunix-2.7.2.1.a(HsUnix.o):(.text+0x50):
first defined here
collect2: error: ld returned 1 exit status
)
```

Any hint on what the problem could be, if it's on my side ?
I get the errors mention unix-2.7.2.1 but it does so during the distributive configure phase, so not really sure where the problem is ..

**Comment by RyanGlScott** [comment]
https://github.com/commercialhaskell/stack/issues/2190 and http://stackoverflow.com/questions/3793571/xmonad-configuration-file-issue suggest the error comes from the fact that you have two different versions of `unix` installed simultaneously. Indeed, the error log you've pasted shows `unix-2.6.0.1` and `unix-2.7.2.1`.

How are you installing `distributive`? One thing to try is what https://github.com/commercialhaskell/stack/issues/2190#issuecomment-286892371 suggests: upgrade to a newer `cabal-install`.

**Comment by Ulrar** [comment]
Allright yes, looks like updating cabal does the trick.
Thanks !
