### ISSUE TITLE
"/usr/bin/ld: cannot find -lHStransformers-compat" and other difficulties

### ISSUE THREAD

**Issue by MonsieurCactus** [ekmett/distributive#9]
I can't seem to install distributive from Cabal.  When on StackOverflow now trying here.  

    > cabal install distributive
    Resolving dependencies...
    [1 of 1] Compiling Main             ( /tmp/distributive-0.4.4-9616/distributive-0.4.4/Setup.lhs, /tmp/distributive-0.4.4-9616/distributive-0.4.4/dist/setup/Main.o )
    Linking /tmp/distributive-0.4.4-9616/distributive-0.4.4/dist/setup/setup ...
    Configuring distributive-0.4.4...
    Building distributive-0.4.4...
    Preprocessing library distributive-0.4.4...
    [1 of 2] Compiling Data.Distributive.Generic ( src/Data/Distributive/Generic.hs, dist/build/Data/Distributive/Generic.o )
    [2 of 2] Compiling Data.Distributive ( src/Data/Distributive.hs, dist/build/Data/Distributive.o )
    /usr/bin/ld: cannot find -lHStransformers-compat-0.4.0.4-ghc7.8.4
    /usr/bin/ld: cannot find -lHStransformers-0.4.3.0-ghc7.8.4
    /usr/bin/ld: cannot find -lHStagged-0.7.3-ghc7.8.4
    collect2: error: ld returned 1 exit status
    Failed to install distributive-0.4.4
    cabal: Error: some packages failed to install:
    distributive-0.4.4 failed during the building phase. The exception was:
    ExitFailure 1

**Comment by ekmett** [comment]
The fact that you can't find _any_ of the dependencies of `distributive` seems to indicate a much broader problem with your install than anything in particular to do with this project.

Can you actually install anything at all?

**Comment by MonsieurCactus** [comment]
All three dependencies are supposedly installed.

    me@ubuntu-14.04:~$ cabal install tagged
    Resolving dependencies...
    All the requested packages are already installed:
    tagged-0.7.3
    Use --reinstall if you want to reinstall anyway.
    me@ubuntu-14.04:~$ cabal install transformers
    Resolving dependencies...
    All the requested packages are already installed:
    transformers-0.4.3.0
    Use --reinstall if you want to reinstall anyway.
    me@ubuntu-14.04:~$ cabal install transformers-compat
    Resolving dependencies...
    All the requested packages are already installed:
    transformers-compat-0.4.0.4
    Use --reinstall if you want to reinstall anyway.

And it in fact seems to be the case 

    me@ubuntu-14.04:~$ ls ~/.cabal/packages/hackage.haskell.org/transformers*
    /home/jdm/.cabal/packages/hackage.haskell.org/transformers:
    0.4.3.0
    
    /home/jdm/.cabal/packages/hackage.haskell.org/transformers-base:
    0.4.4
    
    /home/jdm/.cabal/packages/hackage.haskell.org/transformers-compat:
    0.1.1.1  0.4.0.3  0.4.0.4

**Comment by MonsieurCactus** [comment]
There's not too much literature on this type of error.
    /usr/bin/ld: cannot find -lHStransformers-compat-0.4.0.4-ghc7.8.4

Here is what I found on StackOverflow. No idea where to go next 
* [difficulties installing iHaskell](http://stackoverflow.com/questions/29052530/difficulties-installing-ihaskell)
* [usr/bin/ld: cannot find -l<nameOfTheLibrary>](http://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary?lq=1)

In the second question, the author is *writing* the makefile, which suggests I consult the author of the program.

**Comment by MonsieurCactus** [comment]
When I run in `ghci` (which apparently had been linking to `7.6.3` which I removed), get some feedback about 

    me@ubuntu-14.04:~$ ghci -v
    GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help 
    Glasgow Haskell Compiler, Version 7.8.4, stage 2 booted by GHC version 7.6.3

I found that `[Data.Functor.Reverse](https://hackage.haskell.org/package/transformers-0.3.0.0/docs/Data-Functor-Reverse.html)` is an instance of the `transformers` library:

    Prelude> import Data.Functor.Reverse
    *** Parser:
    
    <no location info>:
        Could not find module ‘Data.Functor.Reverse’
        Perhaps you haven't installed the "dyn" libraries for package ‘transformers-0.4.3.0’?
        Locations searched:
          /home/jdm/.cabal/lib/transformers-0.4.3.0/ghc-7.8.4/Data/Functor/Reverse.dyn_hi

**Comment by ekmett** [comment]
It sounds like your installed versions of `ghc` and `ghc-pkg` are in conflict.

On a Mac I'd just run the uninstaller, and reinstall. I'm not sure quite how I'd try to purge all the Haskell things on Linux, but you'll definitely need to reinstall GHC (and the platform if you installed it) completely.

**Comment by MonsieurCactus** [comment]
They both look good

    me@ubuntu-14.04:~$ ghc -V
    The Glorious Glasgow Haskell Compilation System, version 7.8.4
    me@ubuntu-14.04:~$ ghc-pkg -V
    GHC package manager version 7.8.4

**Comment by ekmett** [comment]
If it isn't the version mismatch, then it may be something with your library path not including wherever your GHC install is putting them.

**Comment by MonsieurCactus** [comment]
Thanks.  Distributive is in place but comonad is giving me difficulty https://github.com/ekmett/semigroupoids/issues/21
